// kahoots.js generado el 2026-05-22
const NEURO1_QUESTIONS = [
  {q:"El sistema nervioso de relación se encarga de:",answers:["Tono muscular, información sensorial, coordinación y equilibrio","Une la vida psíquica con el ambiente exterior","Control automático de las vísceras, trofismo y sistema endocrino","Se encarga de la conexión propioceptiva"],correct:1},
  {q:"Los nódulos de Ranvier:",answers:["Son interrupciones en las vainas de mielina","Se encuentran en las dendritas y facilitan la sinapsis","Dan soporte y fabrican las vainas de mielina","Se encuentran en el botón sináptico"],correct:0},
  {q:"La única función del axón es la conducción del impulso nervioso:",answers:["Falso","Verdadero"],correct:0},
  {q:"El transporte centrípeto en el axón:",answers:["Ocurre desde los botones terminales hacia el soma neuronal","Ocurre desde el soma hacia los botones terminales","Ocurre desde soma a botón terminal y viceversa","Centrípeto es igual que transporte anterógrado"],correct:0},
  {q:"En la sinapsis química la comunicación es unidireccional:",answers:["Verdadero","Falso"],correct:0},
  {q:"En las sinapsis eléctricas los espacios de interconexión:",answers:["Son frecuentes en las neuronas en desarrollo y en las glías","Son frecuentes en las neuronas maduras y en las glías","Son frecuentes en las neuronas maduras y en desarrollo","Son frecuentes únicamente en las glías"],correct:0},
  {q:"Los oligodendrocitos:",answers:["Forman la Vaina de Mielina en el SNC","Actúan frente a la inflamación y daños del tejido nervioso","Forman la Vaina de Mielina en el sistema nervioso periférico","Forman la barrera hematoencefálica"],correct:0},
  {q:"El telencéfalo o cerebro consta de:",answers:["H. cerebral, corteza, stma límbico, núcleos basales, vent. laterales","H. cerebral, corteza, tálamo, n. basales y ventrículos","H. cerebral, corteza, tálamo, n. basales y epitálamo","H. cerebral, corteza, tálamo, n. basales y subtálamo"],correct:0},
  {q:"El LCR circula:",answers:["Entre aracnoides y piamadre","Entre duramadre y aracnoides","Debajo de la piamadre","Encima de la duramadre"],correct:0},
  {q:"En el giro precentral:",answers:["La cabeza está en la parte más inferior del giro","El área representada de la cara es pequeña","La cabeza está en la parte más superior del giro","La mano está representada encima del cuerpo calloso"],correct:0},
  {q:"El campo ocular frontal se encuentra próximo a la cisura longitudinal del hemisferio:",answers:["Verdadero","Falso"],correct:1},
  {q:"En el Hipocampo se produce:",answers:["Se encarga de la memoria y aspectos emocionales de conducta","Responsables de la percepción olfato","Percepción sonido"],correct:0},
  {q:"El estupor:",answers:["Estado inmediato previo al coma","Estado de pérdida de conciencia sin apertura de ojos a estímulos","Somnolencia, desinterés, lentitud de pensamiento","Puede durar hasta alrededor de un mes"],correct:0},
  {q:"La prosopagnosia:",answers:["Incapacidad para reconocer rostros","Incapacidad para reconocer objetos mediante el tacto","Incapacidad para autoreconocernos","Es la imposibilidad de evocar recuerdos"],correct:0},
  {q:"Sinc. de imitación: la contracción de un músculo en el lado sano produce la contracción del mismo en el lado afectado:",answers:["Verdadero","Falso"],correct:0},
  {q:"Afasia de conducción:",answers:["Hablan y comprenden pero con pausas y palabras incorrectas","Alteración de la comprensión del lenguaje","Alteración de la emisión del lenguaje","Incapacidad para nombrar objetos"],correct:0},
  {q:"El prototipo de paciente con ACV:",answers:[">60, arteriosclerosis, HTA, aneurismas, tumores",">70, arteriosclerosis, HTA, aneurismas, tumores",">40, arteriosclerosis, HTA, aneurismas, tumores"],correct:0},
  {q:"En un ACV la zona de penumbra:",answers:["Rodea al núcleo isquémico con flujo menor del 50%","Es el área donde las neuronas no están necróticas","La evolución es rápida y a veces irreversible","Ninguna es correcta"],correct:0},
  {q:"Las neuronas motoras inferiores tienen sus cuerpos celulares en la médula espinal y tronco del encéfalo:",answers:["Verdadero","Falso"],correct:0},
  {q:"La vía piramidal la forman:",answers:["Haz córtico espinal lateral, medial y haz córticonuclear","Haz córtico espinal lateral, medial y haz reticuloespinal","Haz córtico espinal lateral, medial y haz vestibuloespinal","Haz córtico espinal lateral, medial y haz tectoespinal"],correct:0},
  {q:"El tracto córticoespinal ventral se decusa a nivel de la médula oblongada:",answers:["Verdadero","Falso"],correct:1},
  {q:"El tracto tectoespinal:",answers:["Dirige la cabeza y los ojos hacia un objetivo","Permite la estabilidad de la cabeza","Intervienen en el control de la postura","Estimula los músculos flexores e inhibe los extensores"],correct:0},
  {q:"Haz espinotalámico lateral transmite el dolor y la temperatura:",answers:["Verdadero","Falso"],correct:0},
  {q:"La vía piramidal controla la movilidad del tronco y las extremidades:",answers:["Inhibiendo la actividad de la motoneurona","Excitando la actividad de la motoneurona","Inhibiendo y excitando la actividad de la motoneurona","Todas son falsas"],correct:0},
  {q:"Cuando hay ausencia de movimiento voluntario o lentitud para iniciarlo se denomina:",answers:["Bradicinesia","Bradinesia","Hipocinesia","Bradiacinesia","Acinesia"],correct:0},
  {q:"Los gliomas no se originan en neuronas:",answers:["Verdadero","Falso"],correct:0},
  {q:"Definición de tumor cerebral:",answers:["Crecimiento celular anormal","Hemorragia leve","Malformación venosa","Infección bacteriana"],correct:0},
  {q:"Síntoma clave de hipertensión craneal:",answers:["Cefalea","Hipotensión","Anhidrosis","Hipo"],correct:0},
  {q:"Pseudotumor cerebral causa:",answers:["Desequilibrio del LCR","Trombosis venosa","Meningitis bacteriana","Hipertensión arterial"],correct:0},
  {q:"Metástasis cerebrales frecuentes provienen de:",answers:["Pulmón y mama","Estómago solo","Tiroides y colon","Páncreas solo"],correct:0},
  {q:"Manifestación focal de lóbulo frontal:",answers:["Alteraciones cognitivas","Alteraciones visuales","Afasia","Diplopía"],correct:0},
  {q:"¿Demencia más frecuente después de Alzheimer?",answers:["Vascular","Parkinson","Lewy","Frontotemporal"],correct:0},
  {q:"¿Neurotransmisor reducido en Alzheimer?",answers:["Acetilcolina","Dopamina","Serotonina","Noradrenalina"],correct:0},
  {q:"Objetivo de rehabilitación en demencias:",answers:["Compensar deterioro","Curación completa","Aislar paciente","Suspender cuidados"],correct:0},
  {q:"Rasgo clave de demencia con cuerpos de Lewy:",answers:["Alucinaciones visuales","Inicio agudo","Agnosia prominente","Apraxia grave","Euforia persistente"],correct:0},
  {q:"Enfermedad de Pick afecta:",answers:["Lóbulos frontotemporales","Cerebelo solo","Occipital aislado","Tronco cerebral"],correct:0},
  {q:"La demencia afecta memoria y conducta:",answers:["Verdadero","Falso"],correct:0},
  {q:"Síntoma cognitivo temprano típico:",answers:["Amnesia reciente","Agnosia severa","Apraxia grave","Afasia"],correct:0},
  {q:"Función del rubroespinal:",answers:["Activa flexores","Controla visión","Modula dolor","Activa extensores"],correct:0},
  {q:"Tracto que dirige cabeza y ojos:",answers:["Tectoespinal","Grácil","Espinocerebeloso","Cuneiforme"],correct:0},
  {q:"El transporte en el interior del axón puede ser:",answers:["A y B son verdaderas","A - Centrífugo: ocurre desde el soma neuronal hacia el final del axón","B - Centrípeto: ocurre desde los botones terminales hacia el soma neurón","A y B son falsas"],correct:0},
  {q:"En general las neuronas responsables de transmitir la información de los sentidos son:",answers:["Bipolares","Unipolares","Multipolares","Tripolares"],correct:0},
  {q:"4 conexinas forman una conexona en la sinapsis eléctrica:",answers:["Falso","Verdadero"],correct:0},
  {q:"La función de los astrocitos es:",answers:["Formar la barrera hematoencefálica","Formar la vaina de mielina en el SNP","Formar la vaina de mielina en el SNC","Actuar frente a la inflamación y daño en el tejido nervioso"],correct:0},
  {q:"El líquido cefalorraquídeo circula entre:",answers:["Aracnoides y piamadre","Duramadre y aracnoides","Duramadre y piamadre","Paquimeninge y aracnoides"],correct:0},
  {q:"El área de la cabeza se encuentra representado en el lóbulo frontal:",answers:["En la parte más inferior del giro precentral","En la parte más superior del giro precentral","En la parte media del giro precentral","En la parte más medial del hemisferio, sobre el cuerpo calloso"],correct:0},
  {q:"La elaboración y regulación de las respuestas motoras haciéndolas conscientes corresponde al:",answers:["Nivel cortical","Nivel subcortical","Nivel medular","Nivel laberíntico"],correct:0},
  {q:"Las neuronas presentes en ganglio de la raíz posterior son:",answers:["Unipolares","Bipolares","Multipolares","Cuatripolares"],correct:0},
  {q:"Las neuronas se localizan en:",answers:["Encéfalo, médula espinal y ganglios nerviosos","Encéfalo","Médula espinal","Ganglios nerviosos"],correct:0},
  {q:"La sustancia de Nissl en la neurona:",answers:["Sintetiza y transporta proteínas en el interior de la célula","Sintetiza y transporta moléculas en el interior de la célula","Sintetiza y transporta proteínas en el axón de la célula","Sintetiza y transporta proteínas en el botón terminal de la célula"],correct:0},
  {q:"La sinapsis eléctrica utiliza neurotransmisores:",answers:["Falso","Verdadero"],correct:0},
  {q:"En una sinapsis química se le denomina zona activa:",answers:["A la zona de liberación de los neurotransmisores","A la dendrita","Al botón postsináptico","A la zona de recepción de los neurotransmisores"],correct:0},
  {q:"Cual es el neurotransmisor que retiene la información y la almacena:",answers:["Acetilcolina","Dopamina","Noradrenalina","Serotonina"],correct:0},
  {q:"Cuando a una persona le gusta relacionarse con los demás y tener mucha vida social ¿qué neurotransmisor interviene?",answers:["Noradrenalina","Dopamina","Ácido gamma aminobutírico","Acetilcolina"],correct:0},
  {q:"En una sinapsis química:",answers:["Hay retardo sináptico siendo unidireccional","No hay retraso sináptico liberando neurotransmisores","Hay retraso sináptico siendo bidireccional","No hay retraso sináptico siendo bidireccional"],correct:0},
  {q:"Qué es la densidad postsináptica:",answers:["Donde se encuentran los receptores de los neurotransmisores","Donde se libera el neurotransmisor","El cuerpo del botón postsináptico","El espacio entre botón presináptico y postsináptico"],correct:0},
  {q:"Cual es el potencial de reposo de una neurona:",answers:["-70mV","-60mV","-50mV","-80mV"],correct:0},
  {q:"¿Qué neuroglia tiene función fagocitaria?",answers:["Microglia","Astrocito","Oligodendrocito","Células de Schwann"],correct:0},
  {q:"Los receptores cutáneos encargados de percibir la textura son los:",answers:["Discos táctiles de Merkel","Corpúsculos de Vater-Pacini","Manguitos pilosos"],correct:0},
  {q:"Los órganos tendinosos de Golgi se encuentran en los tendones y responden a niveles relativamente altos de tensión:",answers:["Verdadero","Falso"],correct:0},
  {q:"Señala la respuesta verdadera:",answers:["Rojo y amarillo son correctos","La sustancia blanca son las fibras nerviosas","La sustancia blanca son las fibras y somas","La sustancia gris son las células nerviosas"],correct:0},
  {q:"La zona rostral en el sistema nervioso pertenece:",answers:["A la zona más superior del sistema nervioso","A la zona más inferior del sistema nervioso","A la zona más posterior del sistema nervioso","A la zona más anterior del sistema nervioso"],correct:0},
  {q:"El secretor del LCR en el sistema nervioso es:",answers:["Plexo coroideo","Tercer ventrículo","Cuarto ventrículo","Ventrículo lateral"],correct:0},
  {q:"El hemisferio izquierdo prefiere:",answers:["Hablar, escuchar, leer y escribir","Dibujar, escuchar, ver imágenes","Prefiere instrucciones no verbales","Resolver los problemas con intuición"],correct:0},
  {q:"Los gestos emocionales son controlados por:",answers:["Lóbulo frontal","Lóbulo temporal","Lóbulo parietal","Lóbulo occipital"],correct:0},
  {q:"Cuando desviamos la mirada con ambos ojos hacia un mismo lado activamos el campo ocular del lóbulo:",answers:["Frontal","Occipital","Temporal","Parietal"],correct:0},
  {q:"La corteza somatosensorial primaria se encuentra en:",answers:["Lóbulo parietal","Lóbulo frontal","Lóbulo temporal","Lóbulo occipital"],correct:0},
  {q:"El hipocampo y la amígdala forman parte del área límbica siendo sus funciones:",answers:["Hipocampo: memoria y emociones. Amígdala: percepción olfato","Hipocampo: memoria y emociones. Amígdala: entendimiento del lenguaje","Amígdala: memoria y emociones. Hipocampo percepción olfato","Hipocampo: percepción auditiva. Amígdala: entendimiento del lenguaje"],correct:0},
  {q:"El test de Klein es un test para valorar la integridad de:",answers:["La arteria vertebral","Arteria basilar","Carótida interna","Arteria cerebral media"],correct:0},
  {q:"El drenaje de los senos venosos y venas yugulares se realiza a través:",answers:["Del agujero rasgado posterior entre occipucio y temporal","Del agujero rasgado posterior entre occipucio y parietal","Del agujero rasgado anterior entre occipucio y parietal","Del agujero rasgado anterior entre occipucio y temporal"],correct:0},
  {q:"En la fase de estupor el paciente:",answers:["Todas son falsas","Responde a estímulos verbales","El paciente no responde a estímulos dolorosos","El paciente no responde a ningún estímulo"],correct:0},
  {q:"Qué es la prosopagnosia:",answers:["Incapacidad para identificar los rostros","Incapacidad para autoreconocerse","Incapacidad para reconocer objetos con el tacto","Incapacidad de evocar recuerdos"],correct:0},
  {q:"La anartria y disartria son frecuentes en:",answers:["La afasia motora de Brocca","La afasia sensitiva de Wernicke","Afasia sensitiva y motora de Brocca","En ninguna de ellas"],correct:0},
  {q:"Si un paciente tiene agrafía pensaremos en una lesión del lóbulo:",answers:["Frontal","Temporal","Occipital"],correct:0},
  {q:"La desmielinización progresiva es característica de:",answers:["Esclerosis múltiple","Demencia senil","Demencia por cuerpos de Lewy","Parkinson"],correct:0},
  {q:"La estructura anatómica que une ambos hemisferios cerebrales es:",answers:["Cuerpo calloso","Cisura central","Diencéfalo","Circunvoluciones de la corteza cerebral"],correct:0},
  {q:"La decusación de las fibras nerviosas se produce a nivel:",answers:["Bulbo raquídeo","Diencéfalo","Mesencéfalo","Corteza cerebral"],correct:0},
  {q:"En el sistema nervioso central las neuroglías suponen un número mayor que las neuronas:",answers:["9 veces más","20 veces más","No es cierto ambas están en número similar","Las neuronas son más numerosas que las glías"],correct:0},
  // -- Extras vídeo 3 --
  {q:"Las bandas oligoclonales de IgG en el LCR son típicas de:",answers:["ECM","ELA","MENINGITIS","COREOATETOSIS"],correct:0},
  {q:"En el reflejo miotático inverso:",answers:["Al aumentar la tensión del tendón se inhibe la contracción muscular","Al contraer el agonista se relaja el antagonista","Al aumentar la longitud de la fibra muscular provoca una contracción","Ninguna es correcta"],correct:0},
  {q:"La motoneurona alfa:",answers:["Ambas son verdaderas","Se ramifica muchas veces antes de entrar en el músculo","La estimulación de una fibra estimula a varios cientos de fibras musculares","Ambas son falsas"],correct:0},
  {q:"En el enclaustramiento el paciente no puede hacer movimientos por lesión de las vías corticobulbares y corticoespinales:",answers:["Roja y verde son verdaderas","Estando el SRAA intacto","Estando dañado el SRAA","La causa más frecuente es el infarto o hemorragia protuberancial"],correct:0},
  {q:"Si hay una fractura del etmoides hay riesgo de ageusia:",answers:["Falso","Verdadero"],correct:0},
  {q:"Si vemos a un paciente en la calle caminar con la cabeza inclinada de forma constante podemos pensar en:",answers:["Afectación del IV par craneal","Afectación del VI par craneal","Afectación del X par craneal","Afectación del III par craneal"],correct:0},
  {q:"Si al percutir con el diapasón y colocarlo en la mastoides lo oímos más que al lado del oído es porque:",answers:["Existe lesión de la vía área","Existe lesión de la vía ósea","Existe lesión de la vía área y ósea","No existe lesión, es normal"],correct:0},
  {q:"Los dos tercios anteriores de la lengua sensitivamente están inervados por:",answers:["Facial","Hipogloso","Glosofaríngeo","Trigémino"],correct:0},
  {q:"En la parálisis de Duchene ERB:",answers:["Existe pronación del antebrazo","Existe supinación del antebrazo","Existe flexión de codo","Existe rotación externa de hombro"],correct:0},
  {q:"En la Miastenia Gravis:",answers:["Hay una afectación del III par craneal","Afectación del II par craneal","Afectación del VI par craneal","Afectación del V par craneal"],correct:0},
  {q:"En la pregunta sobre la parálisis de Duchene hemos dicho que el brazo se mantiene en supinación:",answers:["Falso","Verdadero"],correct:0},
  {q:"La Enfermedad de Bisgwanger:",answers:["Es una demencia de origen vascular","Es una demencia de origen metabólico","Es una demencia de origen infeccioso","Es una demencia de origen degenerativo"],correct:0},
  {q:"El neurotransmisor más afectado en la enfermedad de Alzheimer es:",answers:["Roja y verde son verdaderas (acetilcolina y glutamato)","Acetilcolina","Glutamato","Somatostatina"],correct:0},
  {q:"La Tríada de Cushing se caracteriza por:",answers:["Hipertensión, bradicardia y alteraciones respiratorias","Hipotensión, bradicardia y alteraciones respiratorias","Hipertensión, taquicardia sin alteraciones respiratorias","Hipertensión, taquicardia y alteraciones respiratorias"],correct:0},
  {q:"Las metástasis cerebrales más frecuentes son:",answers:["Cáncer pulmonar, cáncer de mama, melanoma y cáncer de riñón","Osteosarcoma, melanoma y cáncer pulmonar","Cáncer de mama, cáncer de páncreas, cáncer de colon, cáncer pulmonar","Cáncer de estómago, cáncer pulmonar, melanoma, linfomas"],correct:0}
];

const RESPI1_QUESTIONS = [
  {q:"A la transmisión zoonótica directa también se le denomina:",answers:["Spillover","Spillewer","Transmisión interanimal","Transmisión intrazoonótica"],correct:0},
  {q:"La HIPOPNEA es toda disminución del flujo basal aéreo superior al:",answers:["50%","30%","70%","10%"],correct:0},
  {q:"En la enfermedad tromboembólica venosa el riesgo de embolia pulmonar es mayor en:",answers:["Los primeros días de formarse el trombo","En los últimos días de formarse el trombo","Al principio y al final de formarse el trombo","Nunca hay riesgo"],correct:0},
  {q:"Qué signo es característico en el síndrome mediastínico posterior:",answers:["Roja y amarilla son verdaderas","Disfagia","Disnea","Dolor interescapular"],correct:0},
  {q:"Cuál es el derrame pleural más frecuente:",answers:["Trasudativo","Trasehepático","Exudativo","Hepático"],correct:0},
  {q:"Qué son los Criterios de Jones y Brosseau:",answers:["Condiciones para demostrar la transmisión de SARS-CoV-2 mediante aerosoles","Condiciones para demostrar la transmisión de SARS-CoV-2 mediante contacto","Condiciones para demostrar la transmisión de SARS-CoV-2 mediante animales","Condiciones para demostrar la transmisión de SARS-CoV-2 en general"],correct:0},
  {q:"Los anticuerpos IgM en la infección de Covid 19 aparecen a los 15 días:",answers:["Falso","Verdadero"],correct:0},
  {q:"La neumonía micótica es causada por el hongo Pneumocystis jirovecii. Relacionado con:",answers:["SIDA","TUBERCULOSIS","ESCLEROSIS MÚLTIPLE","COVID 19"],correct:0},
  {q:"En el patrón ventilatorio obstructivo:",answers:["FEV1 disminuido","FEV1/FVC >70%","FVC aumentado","FEV1 aumentado"],correct:0},
  {q:"La radiografía torácica en nido de golondrina es típica de:",answers:["Bronquiectasia","Neumonía","Enfisema","Atelectasia"],correct:0},
  {q:"Una compliance disminuida es frecuente en la enfermedad restrictiva pulmonar:",answers:["Verdadero","Falso"],correct:0},
  {q:"Cuando un paciente acude a nuestra consulta y nos comenta que el médico le ha prescrito surfactante pulmonar:",answers:["Significa que puede tener atelectasia","Significa que puede tener neumonía","Significa que puede tener enfisema","Significa que puede tener insuficiencia respiratoria"],correct:0},
  {q:"Si en una espirometría le digo al paciente que coja todo el aire y lo expulse hasta quedarse sin nada en el menor tiempo:",answers:["CVF","VMM","CV","CPT"],correct:0},
  {q:"A la máxima cantidad de aire que se queda dentro de los pulmones después de una inspiración máxima se le denomina:",answers:["Capacidad pulmonar total","Capacidad inspiratoria","Capacidad funcional residual","Capacidad vital"],correct:0}
];
